2025-04-19 16:00:01,177 INFO    MainThread:36668 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Usuario\ML_Proyect_6\deep\wandb\run-20250419_160001-gbqv8sw6\logs\debug.log
2025-04-19 16:00:01,177 INFO    MainThread:36668 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Usuario\ML_Proyect_6\deep\wandb\run-20250419_160001-gbqv8sw6\logs\debug-internal.log
2025-04-19 16:00:01,178 INFO    MainThread:36668 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000025A94DDE060>
2025-04-19 16:00:01,178 INFO    MainThread:36668 [wandb_init.py:init():761] calling init triggers
2025-04-19 16:00:01,178 INFO    MainThread:36668 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'batch_size': 32, 'img_size': 224, 'epochs': 20, 'patience': 5, 'base_model': 'resnet101', 'learning_rate': 0.001, 'weight_decay': 0.0001, 'unfreeze_layers': 3, '_wandb': {}}
2025-04-19 16:00:01,178 INFO    MainThread:36668 [wandb_init.py:init():784] starting backend
2025-04-19 16:00:01,178 INFO    MainThread:36668 [wandb_init.py:init():788] sending inform_init request
2025-04-19 16:00:01,180 INFO    MainThread:36668 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-19 16:00:01,183 INFO    MainThread:36668 [wandb_init.py:init():798] backend started and connected
2025-04-19 16:00:01,190 INFO    MainThread:36668 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-19 16:00:01,190 INFO    MainThread:36668 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-19 16:00:01,191 INFO    MainThread:36668 [wandb_init.py:init():891] updated telemetry
2025-04-19 16:00:01,196 INFO    MainThread:36668 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-19 16:00:02,695 INFO    MainThread:36668 [wandb_init.py:init():990] starting run threads in backend
2025-04-19 16:00:03,290 INFO    MainThread:36668 [wandb_run.py:_console_start():2375] atexit reg
2025-04-19 16:00:03,291 INFO    MainThread:36668 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-19 16:00:03,291 INFO    MainThread:36668 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-19 16:00:03,291 INFO    MainThread:36668 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-19 16:00:03,292 INFO    MainThread:36668 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-19 16:21:57,001 INFO    MainThread:36668 [wandb_run.py:_finish():2112] finishing run 201905882-icai/deep-lab-models/gbqv8sw6
2025-04-19 16:21:57,011 INFO    MainThread:36668 [jupyter.py:save_history():458] not saving jupyter history
2025-04-19 16:21:57,011 INFO    MainThread:36668 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-19 16:21:57,011 INFO    MainThread:36668 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-19 16:21:57,011 INFO    MainThread:36668 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-04-19 16:21:57,012 INFO    MainThread:36668 [wandb_run.py:_restore():2322] restore
2025-04-19 16:21:57,012 INFO    MainThread:36668 [wandb_run.py:_restore():2328] restore done
2025-04-19 16:22:05,187 INFO    MainThread:36668 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-19 16:22:05,188 INFO    MainThread:36668 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-19 16:22:05,192 INFO    MainThread:36668 [wandb_run.py:_footer_sync_info():3917] logging synced files
